branches:
  only:
    - master

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - build-essential
    - zlib1g-dev
    - libncurses5-dev
    - libssl-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ];
    then
      export CC="gcc-4.9";
      export CXX="g++-4.9";
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
      cd -;
    fi;

before_script:
  - sudo rm -rf /usr/local/clang*
  - sudo rm -rf /var/lib/apt/lists/*
  - wget http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar xvf clang*
  - cd clang*
  - sudo cp -r * /usr/local/ && cd ..
  - git clone https://github.com/ponylang/ponyc
  - cd ponyc
  - make config=release
  - export PATH=$PATH:$PWD/build/release/
  - cd ..

script:
  - ponyc jennet && ./jennet/jennet
  - ponyc examples/basicauth
  - ponyc examples/params
  - ponyc examples/servedir
  - ponyc examples/servefile
